# Site settings
title: '#play14'
email: team@play14.org
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://play14team.github.io/play14-website" # the base hostname & protocol for your site
twitter_username: play14team
github_username:  play14team

# Build settings
markdown: kramdown

paginate: 4
paginate_path: "blog/page:num"

gems:
   - jekyll-paginate
   - jekyll-sitemap
   - jekyll-feed
#   - jekyll-mentions
#   - jemoji
#   - jekyll-redirect-from
