# Site settings
title: '#play14'
email: team@play14.org
description: > # this means to ignore newlines until "baseurl:"
  '#play14 : We believe in playfulness.
  An international gathering for people who share the idea that playing is a great way to teach, learn and understand!'
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://play14team.github.io" # the base hostname & protocol for your site
twitter_username: play14team
github_username:  play14team

# Build settings
markdown: kramdown

paginate: 4
paginate_path: "blog/page:num"

gems:
   - jekyll-paginate
   - jekyll-sitemap
   - jekyll-feed
#   - jekyll-mentions
#   - jemoji
#   - jekyll-redirect-from

collections:
  events:
    output: true
    permalink: :collection/:categories/:path
  games:
    output: true
    permalink: :collection/:path

defaults:
  - scope:
      path: ""
      type: "events"
    values:
      layout: "event"
  - scope:
      path: ""
      type: "games"
    values:
      layout: "game"

permalink: pretty

